### ISSUE TITLE
是否考虑导入本地音、视频的功能？

### ISSUE THREAD

**Issue by guangxuanliu** [bigzhu/EbuoyDoc#3]
很喜欢这款app的学习英语的方法，但是目前仅支持youtube的视频。

学英语的过程中，难免有一些听力材料是从网上下载到本地的，比如雅思的听力音频，也想用这种方法来学习，想问一下作者是否还在维护，是否考虑导入本地音、视频的功能？

**Comment by bigzhu** [comment]
本地的音频 视频 需要有匹配的带时间线的字幕，一般用户很难提供对应的资源。

**Comment by guangxuanliu** [comment]
明白。但是我有一个疑问，可否用一些语音识别库，识别语音，然后自动生成字幕呢？

**Comment by bigzhu** [comment]
可以，但是有以下两个问题：
1. 识别库运行成本太高。
2. 识别存在误差，容易误导学习的人，与其这样，不如使用有相对精准字幕的。
感谢你的意见
